#!/usr/bin/env -S python -tt
# -*- coding: utf-8 -*-
import logging
import sys

import click
from dotenv import load_dotenv

from firefly.client import FireflyClient
from firefly.config import load_config
from firefly.exporter import Exporter
from storage.transactions import TransactionsDB
from moneywiz.importer import CsvImporter
from moneywiz.analyzer import CsvAnalyzer


@click.command()
@click.option('--dbpath', default='.db', type=click.Path(exists=False), help='DB directory')
@click.option('--url', help='Firefly III URL')
@click.option('--token', help='Firefly III token')
@click.option('--export/--import', is_flag=True, default=False, help='Export or import mode')
@click.option('--config', type=click.Path(exists=True), help='Configuration file for export')
@click.option('-v', is_flag=True, default=False, help='Verbose logging')
@click.argument('filename', type=click.Path(exists=True), required=False)
def cli(dbpath, url, token, export, config, v, filename):
    logging.getLogger("sqlalchemy.engine").setLevel(logging.DEBUG if v else logging.WARN)
    logging.getLogger("firefly_iii_client").setLevel(logging.DEBUG if v else logging.WARN)
    logging.getLogger("urllib3").setLevel(logging.DEBUG if v else logging.WARN)
    logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', level=logging.DEBUG if v else logging.INFO)
    logger = logging.getLogger(__name__)

    db = TransactionsDB(logger, dbpath).init()

    if not export:
        if filename is None:
            raise click.UsageError("The filename is required in the import mode.")

        importer = CsvImporter(logger)
        analyzer = CsvAnalyzer(logger, db)

        try:
            data = importer.parse(filename)
            analyzer.analyze(data)
            analyzer.commit()
        except Exception as e:
            logger.error(f'Failed to import CSV file: {e}', exc_info=True)
            sys.exit(1)

    else:
        if url is None:
            raise click.UsageError("The Firefly URL is required in the export mode.")
        if token is None:
            raise click.UsageError("The Firefly token is required in the export mode.")

        exporter = Exporter(logger, db, FireflyClient(logger, url, token), load_config(logger, config))

        try:
            exporter.export()
        except Exception as e:
            logger.error(f'Failed to export to Firefly III: {e}', exc_info=True)
            sys.exit(2)


# main block
if __name__ == '__main__':
    load_dotenv()
    cli(auto_envvar_prefix='FIREFLY')
