#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import sys

import click

from txsdb import TxsDatabase
from txsimporter import TxsImporter


@click.command()
@click.option('--dbpath', default='.db', type=click.Path(exists=False), help='DB directory')
@click.option('-v', default=False, is_flag=True, help='Verbose logging', required=False)
@click.argument('filename', type=click.Path(exists=True), required=True)
def cli(dbpath, v, filename):
    logging.getLogger("sqlalchemy.engine").setLevel(logging.DEBUG if v else logging.WARN)
    logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', level=logging.DEBUG if v else logging.INFO)
    logger = logging.getLogger(__name__)

    db = TxsDatabase(logger, dbpath)
    try:
        db.init()
    except Exception as e:
        logger.error(f'Failed to initialize database: {e}')
        sys.exit(1)

    importer = TxsImporter(logger, db)
    try:
        importer.parse(filename)
    except Exception as e:
        logger.error(f'Failed to parse CSV file: {e}')
        sys.exit(2)


# main block
if __name__ == '__main__':
    cli()
