#!/usr/bin/env python
# -*- coding: utf-8 -*-
import logging
import sys

import click

from storage.transactions import TransactionsDB
from moneywiz.importer import CsvImporter
from moneywiz.analyzer import CsvAnalyzer


@click.command()
@click.option('--dbpath', default='.db', type=click.Path(exists=False), help='DB directory')
@click.option('-import-only', default=False, is_flag=True, help='Import only', required=False)
@click.option('-v', default=False, is_flag=True, help='Verbose logging', required=False)
@click.argument('filename', type=click.Path(exists=True), required=True)
def cli(dbpath, import_only, v, filename):
    logging.getLogger("sqlalchemy.engine").setLevel(logging.DEBUG if v else logging.WARN)
    logging.basicConfig(format='%(asctime)s - %(levelname)s - %(message)s', level=logging.DEBUG if v else logging.INFO)
    logger = logging.getLogger(__name__)

    db = TransactionsDB(logger, dbpath)
    importer = CsvImporter(logger)
    analyzer = CsvAnalyzer(logger)

    try:
        data = importer.parse(filename)
        analyzer.analyze(data)
        analyzer.commit(db.init())
    except Exception as e:
        logger.error(f'Failed to import CSV file: {e}')
        sys.exit(1)


# main block
if __name__ == '__main__':
    cli()
